<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Teste</AssemblyName>
    <RootNamespace>Teste</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Teste.Shared\Teste.Shared.csproj" />
  </ItemGroup>
</Project>